// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace macro_utils_h_generator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class macro_utils_generated : macro_utils_generatedBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

/*THIS FILE IS GENERATED*/
/*DO NOT EDIT BY HAND!!!*/
/*instead edit macro_utils_generated.tt here: http://www.github.com/azure/macro-utils-c.git */

");
            
            #line 14 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
/*CHANGE BELOW 2 VARIABLES TO GET MORE / LESS */ 
            
            #line default
            #line hidden
            
            #line 15 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
int nArithmetic=2048;
            
            #line default
            #line hidden
            
            #line 16 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
int nMacroParameters=140;
    /*127 parameters in one macro definition in C99 in chapter 5.2.4.1 Translation limits*/
    /* 11 Apr 2023: VS 17.5.3 doesn't have a limit of 127 (compiler version is 19.35.32216.1), updating to 140 to allow upstream projects to use more parameters. Note: use sensible increments, compilation time suffers!*/

            
            #line default
            #line hidden
            this.Write("\r\n#ifndef MACRO_UTILS_GENERATED_H\r\n#define MACRO_UTILS_GENERATED_H\r\n\r\n#define MU_" +
                    "C2INTERNAL_(x,y) x##y\r\n#define MU_C2INTERNAL(x,y) MU_C2INTERNAL_(x,y)\r\n\r\n#define" +
                    " MU_IFCOMMA(N) MU_C2(MU_IFCOMMA_, N)\r\n#define MU_IFCOMMA_0\r\n#define MU_IFCOMMA_2" +
                    "\r\n");
            
            #line 30 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=4;i<=nMacroParameters;i+=2)
            
            #line default
            #line hidden
            
            #line 31 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_IFCOMMA_");
            
            #line 32 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" ,\r\n");
            
            #line 33 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_IFCOMMALOGIC(N) MU_C2(MU_IFCOMMALOGIC_, N)\r\n#define MU_IFCOMMALOGIC_" +
                    "0\r\n");
            
            #line 37 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=1;i<=nMacroParameters;i+=1)
            
            #line default
            #line hidden
            
            #line 38 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_IFCOMMALOGIC_");
            
            #line 39 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" ,\r\n");
            
            #line 40 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_IFCOMMA_NOFIRST(N) MU_C2(MU_IFCOMMA_NOFIRST, N)\r\n#define MU_IFCOMMA_" +
                    "NOFIRST1\r\n");
            
            #line 44 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=2;i<=nMacroParameters;i++)
            
            #line default
            #line hidden
            
            #line 45 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_IFCOMMA_NOFIRST");
            
            #line 46 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" ,\r\n");
            
            #line 47 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_DEC(x) MU_C2(MU_DEC,x)\r\n");
            
            #line 50 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nArithmetic;i>=1;i--)
            
            #line default
            #line hidden
            
            #line 51 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_DEC");
            
            #line 52 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 52 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-1));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 53 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_INC(x) MU_C2(MU_INC,x)\r\n");
            
            #line 56 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nArithmetic;i>=0;i--)
            
            #line default
            #line hidden
            
            #line 57 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_INC");
            
            #line 58 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 58 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i+1));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 59 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_DIV2(x) MU_C2(MU_DIV2_,x)\r\n\r\n");
            
            #line 63 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nArithmetic;i>=0;i--)
            
            #line default
            #line hidden
            
            #line 64 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_DIV2_");
            
            #line 65 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 65 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i/2));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 66 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 68 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
/*the below produces MOD2 for numbers*/
            
            #line default
            #line hidden
            this.Write("#define MU_MOD2(x) MU_C2(MU_MOD2_,x)\r\n");
            
            #line 70 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nArithmetic;i>=0;i--)
            
            #line default
            #line hidden
            
            #line 71 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_MOD2_");
            
            #line 72 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 72 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i%2));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 73 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_THE_NTH_ARG(");
            
            #line 75 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=1;i<=nMacroParameters;i++)
            
            #line default
            #line hidden
            
            #line 76 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 76 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 76 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(" ... ) P");
            
            #line 76 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nMacroParameters));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n#define MU_COUNT_1_OR_MORE_ARG(...) MU_THE_NTH_ARG (__VA_ARGS__, \\\r\n");
            
            #line 79 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters-1;i>=1;i--){
            
            #line default
            #line hidden
            
            #line 79 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i.ToString()+((i>1)?", ":"")));
            
            #line default
            #line hidden
            
            #line 79 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(@")

/*note: F533AD67_7A90_4DC2_A30A_75306900ACE6 is a guid only used here for the purpose of avoiding clashes with other tokens*/
/*the trick here is to insert an EXTRA token (F533AD67_7A90_4DC2_A30A_75306900ACE6), count the __VA_ARGS__ AND this extra token, and then return the number -1*/
#define MU_COUNT_ARG(...) MU_DEC(MU_COUNT_1_OR_MORE_ARG(F533AD67_7A90_4DC2_A30A_75306900ACE6 __VA_OPT__(,) __VA_ARGS__))

/*note: C5942A16_89D5_4732_8BA4_DCD1B9661DB0 is a GUID that is unique for the purpose of avoiding clashes with other tokens*/
/*__VA_OPT__(1A0D532B_BC7E_4F89_9F1F_831A9C6AF51F) expands to exactly the token C5942A16_89D5_4732_8BA4_DCD1B9661DB0 if the __VA_ARGS__ is non-empty*/
#define MU_ISEMPTY(...) MU_IS_EMPTY_IMPL(__VA_OPT__(C5942A16_89D5_4732_8BA4_DCD1B9661DB0))
#define MU_IS_EMPTY_IMPL(x) MU_IS_EMPTY_PICK_##x
#define MU_IS_EMPTY_PICK_ 1                                         /*for the case when __VA_ARGS__ is empty. */
#define MU_IS_EMPTY_PICK_C5942A16_89D5_4732_8BA4_DCD1B9661DB0 0     /*for the case when __VA_ARGS__ is non-empty*/


");
            
            #line 93 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=1;i--)
            
            #line default
            #line hidden
            
            #line 94 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_1_");
            
            #line 95 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 95 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 95 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 95 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\n");
            
            #line 96 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("X(P");
            
            #line 96 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 96 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 99 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 101 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=1;i--)
            
            #line default
            #line hidden
            
            #line 102 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_1A_");
            
            #line 103 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 103 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 103 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 103 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\n");
            
            #line 104 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("X(P");
            
            #line 104 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 104 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 107 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 109 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=1;i--)
            
            #line default
            #line hidden
            
            #line 110 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_1B_");
            
            #line 111 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 111 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 111 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 111 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\n");
            
            #line 112 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("X(P");
            
            #line 112 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 112 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 115 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(@"
#define MU_FOR_EACH_1(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_1_,MU_COUNT_ARG(__VA_ARGS__)) ( MACRO_TO_INVOKE, __VA_ARGS__)
#define MU_FOR_EACH_1A(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_1A_,MU_COUNT_ARG(__VA_ARGS__)) ( MACRO_TO_INVOKE, __VA_ARGS__)
#define MU_FOR_EACH_1B(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_1B_,MU_COUNT_ARG(__VA_ARGS__)) ( MACRO_TO_INVOKE, __VA_ARGS__)

");
            
            #line 121 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=1;i--)
            
            #line default
            #line hidden
            
            #line 122 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_1_PASTE_");
            
            #line 123 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(PASTE, ");
            
            #line 123 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 123 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 123 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\n");
            
            #line 124 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("MU_C2INTERNAL(PASTE, P");
            
            #line 124 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 124 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 127 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_FOR_EACH_1_PASTE(PASTE, ...) MU_C2(MU_FOR_EACH_1_PASTE_,MU_COUNT_ARG" +
                    "(__VA_ARGS__)) ( PASTE, __VA_ARGS__)\r\n\r\n");
            
            #line 131 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=1;i--)
            
            #line default
            #line hidden
            
            #line 132 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_1_KEEP_1_");
            
            #line 133 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, keep, ");
            
            #line 133 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 133 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+(j<i?", ":"")));
            
            #line default
            #line hidden
            
            #line 133 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\n");
            
            #line 134 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("X(keep, P");
            
            #line 134 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 134 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 137 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_FOR_EACH_1_KEEP_1_0(MACRO_TO_INVOKE, ...) /*expands to nothing*/\r\n\r\n" +
                    "#define MU_FOR_EACH_1_KEEP_1(MACRO_TO_INVOKE, KEEP, ...) MU_C2(MU_FOR_EACH_1_KEE" +
                    "P_1_, MU_COUNT_ARG(__VA_ARGS__))( MACRO_TO_INVOKE, KEEP, __VA_ARGS__)\r\n\r\n");
            
            #line 143 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=1;i--)
            
            #line default
            #line hidden
            
            #line 144 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_1_KEEP_2_");
            
            #line 145 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, KEEP1, KEEP2, ");
            
            #line 145 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 145 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+(j<i?", ":"")));
            
            #line default
            #line hidden
            
            #line 145 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\n");
            
            #line 146 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("X(KEEP1, KEEP2, P");
            
            #line 146 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 146 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 149 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_FOR_EACH_1_KEEP_2_0(...)\r\n\r\n#define MU_FOR_EACH_1_KEEP_2(MACRO_TO_IN" +
                    "VOKE, KEEP1, KEEP2, ...) MU_C2(MU_FOR_EACH_1_KEEP_2_, MU_COUNT_ARG(__VA_ARGS__))" +
                    " ( MACRO_TO_INVOKE, KEEP1, KEEP2, __VA_ARGS__)\r\n\r\n");
            
            #line 155 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=2;i-=2)
            
            #line default
            #line hidden
            
            #line 156 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_2_KEEP_1_");
            
            #line 157 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, KEEP, ");
            
            #line 157 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 157 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+(j<i?", ":"")));
            
            #line default
            #line hidden
            
            #line 157 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\n");
            
            #line 158 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=i;j>=2;j-=2){
            
            #line default
            #line hidden
            this.Write("X(KEEP, P");
            
            #line 158 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-j+1));
            
            #line default
            #line hidden
            this.Write(", P");
            
            #line 158 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-j+2));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 158 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 161 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_FOR_EACH_2_KEEP_1_1(...)\r\n\r\n#define MU_FOR_EACH_2_KEEP_1_0(...)\r\n\r\n#" +
                    "define MU_FOR_EACH_2_KEEP_1(MACRO_TO_INVOKE, KEEP, ...) MU_C2(MU_FOR_EACH_2_KEEP" +
                    "_1_, MU_COUNT_ARG(__VA_ARGS__)) ( MACRO_TO_INVOKE, KEEP, __VA_ARGS__)\r\n\r\n\r\n");
            
            #line 170 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=2;i-=2)
            
            #line default
            #line hidden
            
            #line 171 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_2_KEEP_2_");
            
            #line 172 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, KEEP1, KEEP2, ");
            
            #line 172 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 172 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+(j<i?", ":"")));
            
            #line default
            #line hidden
            
            #line 172 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\n");
            
            #line 173 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=i;j>=2;j-=2){
            
            #line default
            #line hidden
            this.Write("X(KEEP1, KEEP2, P");
            
            #line 173 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-j+1));
            
            #line default
            #line hidden
            this.Write(", P");
            
            #line 173 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-j+2));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 173 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 176 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_FOR_EACH_2_KEEP_2_1(...)\r\n\r\n#define MU_FOR_EACH_2_KEEP_2_0(...)\r\n\r\n#" +
                    "define MU_FOR_EACH_2_KEEP_2(MACRO_TO_INVOKE, KEEP1, KEEP2, ...) MU_C2(MU_FOR_EAC" +
                    "H_2_KEEP_2_, MU_COUNT_ARG(__VA_ARGS__)) ( MACRO_TO_INVOKE, KEEP1, KEEP2, __VA_AR" +
                    "GS__)\r\n\r\n\r\n");
            
            #line 185 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=2;i-=2)
            
            #line default
            #line hidden
            
            #line 186 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_2_");
            
            #line 187 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 187 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 187 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 187 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\n");
            
            #line 188 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=i;j>=2;j-=2){
            
            #line default
            #line hidden
            this.Write("X(P");
            
            #line 188 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-j+1));
            
            #line default
            #line hidden
            this.Write(", P");
            
            #line 188 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-j+2));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 188 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 191 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_FOR_EACH_2_0(...)\r\n\r\n#define MU_FOR_EACH_2(MACRO_TO_INVOKE, ...) MU_" +
                    "C2(MU_FOR_EACH_2_, MU_COUNT_ARG(__VA_ARGS__)) ( MACRO_TO_INVOKE, __VA_ARGS__)\r\n\r" +
                    "\n\r\n\r\n\r\n");
            
            #line 200 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=2;i-=2)
            
            #line default
            #line hidden
            
            #line 201 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_2_REVERSE_");
            
            #line 202 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 202 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 202 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 202 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\n");
            
            #line 203 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=i;j>=2;j-=2){
            
            #line default
            #line hidden
            this.Write("X(P");
            
            #line 203 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j-1));
            
            #line default
            #line hidden
            this.Write(", P");
            
            #line 203 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 203 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 206 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_FOR_EACH_2_REVERSE_0(...)\r\n\r\n#define MU_FOR_EACH_2_REVERSE(MACRO_TO_" +
                    "INVOKE, ...) MU_C2(MU_FOR_EACH_2_REVERSE_, MU_COUNT_ARG(__VA_ARGS__)) ( MACRO_TO" +
                    "_INVOKE, __VA_ARGS__)\r\n\r\n\r\n");
            
            #line 213 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=1;i--)
            
            #line default
            #line hidden
            
            #line 214 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_1_COUNTED_");
            
            #line 215 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 215 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 215 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 215 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\n");
            
            #line 216 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=i;j>=1;j--){
            
            #line default
            #line hidden
            this.Write("X(");
            
            #line 216 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(", P");
            
            #line 216 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-j+1));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 216 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 219 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_FOR_EACH_1_COUNTED_0(...)\r\n\r\n#define MU_FOR_EACH_1_COUNTED(MACRO_TO_" +
                    "INVOKE, ...) MU_C2(MU_FOR_EACH_1_COUNTED_, MU_COUNT_ARG(__VA_ARGS__)) ( MACRO_TO" +
                    "_INVOKE,  __VA_ARGS__)\r\n\r\n\r\n\r\n");
            
            #line 227 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=1;i--)
            
            #line default
            #line hidden
            
            #line 228 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_1_KEEP_2_COUNTED_");
            
            #line 229 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, KEEP1, KEEP2, ");
            
            #line 229 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 229 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 229 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\n");
            
            #line 230 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=i;j>=1;j--){
            
            #line default
            #line hidden
            this.Write("X(");
            
            #line 230 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(", KEEP1, KEEP2, P");
            
            #line 230 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-j+1));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 230 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 233 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_FOR_EACH_1_KEEP_2_COUNTED_0(...)\r\n\r\n#define MU_FOR_EACH_1_KEEP_2_COU" +
                    "NTED(MACRO_TO_INVOKE, KEEP1, KEEP2, ...) MU_C2(MU_FOR_EACH_1_KEEP_2_COUNTED_, MU" +
                    "_COUNT_ARG(__VA_ARGS__)) ( MACRO_TO_INVOKE, KEEP1, KEEP2, __VA_ARGS__)\r\n\r\n\r\n\r\n");
            
            #line 241 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=1;i--)
            
            #line default
            #line hidden
            
            #line 242 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_1_KEEP_1_COUNTED_");
            
            #line 243 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, KEEP, ");
            
            #line 243 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 243 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 243 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\n");
            
            #line 244 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=i;j>=1;j--){
            
            #line default
            #line hidden
            this.Write("X(");
            
            #line 244 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(", KEEP, P");
            
            #line 244 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-j+1));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 244 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 247 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_FOR_EACH_1_KEEP_1_COUNTED_0(...)\r\n\r\n#define MU_FOR_EACH_1_KEEP_1_COU" +
                    "NTED(MACRO_TO_INVOKE, KEEP, ...) MU_C2(MU_FOR_EACH_1_KEEP_1_COUNTED_, MU_COUNT_A" +
                    "RG(__VA_ARGS__)) ( MACRO_TO_INVOKE, KEEP, __VA_ARGS__)\r\n\r\n\r\n\r\n\r\n");
            
            #line 256 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=2;i-=2)
            
            #line default
            #line hidden
            
            #line 257 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_2_COUNTED_");
            
            #line 258 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 258 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 258 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 258 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\n");
            
            #line 259 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=i;j>=1;j-=2){
            
            #line default
            #line hidden
            this.Write("X(");
            
            #line 259 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(", P");
            
            #line 259 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-j+1));
            
            #line default
            #line hidden
            this.Write(", P");
            
            #line 259 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-j+2));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 259 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 262 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write(@"
#define MU_FOR_EACH_2_COUNTED_0(...)

/*the COUNTED breed of MU_FOR_EACH macro invokes a macro with 3 parameters: 1st being the count of invocation. For example.
MU_FOR_EACH_2_COUNTED(MACRO, a,b,c,d,e,f) will result in
MACRO(6, a,b)
MACRO(4, c,d)
MACRO(2, e,f)
This macro exists because we need a ""stop condition"" in outputting COMMA... when calling a function f(a,b,c,d) cannot be f(a,b,c,d,) <=doesn't compile (as opposed to enum definition)
*/
/*MU_FOR_EACH_2_REVERSE acts just like MU_FOR_EACH_2, but in reverse order. Example:
MU_FOR_EACH_2_REVERSE(X,a,b,c,d,e,f) => X(e,f) X(c,d) X (a, b) in this order */


#define MU_FOR_EACH_2_COUNTED(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_2_COUNTED_, MU_COUNT_ARG(__VA_ARGS__)) ( MACRO_TO_INVOKE,  __VA_ARGS__)


/*MU_DO and MU_DO_ASC macros serve the same purpose: call MACRO with an index from 0 to MAX_RANGE_ARG (MU_DO_ASC) or from MAX_RANGE_ARG to 0 (MU_DO).*/

");
            
            #line 282 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=0;i--){
            
            #line default
            #line hidden
            this.Write("#define MU_DO_");
            
            #line 283 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(MACRO, ...) \\\r\n");
            
            #line 284 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=i;j>=0;j--){
            
            #line default
            #line hidden
            this.Write("MACRO(");
            
            #line 284 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(", __VA_ARGS__) ");
            
            #line 284 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 287 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_DO(MAX_RANGE_ARG, MACRO, ...) MU_C2(MU_DO_, MAX_RANGE_ARG)(MACRO, __" +
                    "VA_ARGS__)\r\n\r\n");
            
            #line 291 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var i=nMacroParameters;i>=0;i--){
            
            #line default
            #line hidden
            this.Write("#define MU_DO_ASC_");
            
            #line 292 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(MACRO, ...) \\\r\n");
            
            #line 293 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
for(var j=0;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("MACRO(");
            
            #line 293 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j));
            
            #line default
            #line hidden
            this.Write(", __VA_ARGS__) ");
            
            #line 293 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 296 "D:\r\macro-utils-c\macro_utils_h_generator\macro_utils_generated.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_DO_ASC(MAX_RANGE_ARG, MACRO, ...) MU_C2(MU_DO_ASC_, MAX_RANGE_ARG)(M" +
                    "ACRO, __VA_ARGS__)\r\n\r\n#endif /*MACRO_UTILS_GENERATED_H*/\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public class macro_utils_generatedBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
