// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace macro_utils_h_generator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class macro_utils : macro_utilsBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

/*THIS FILE IS GENERATED*/
/*DO NOT EDIT BY HAND!!!*/
/*instead edit macro_utils.tt here: http://www.github.com/azure/azure-macro-utils-c.git */

");
            
            #line 14 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
/*CHANGE BELOW 2 VARIABLES TO GET MORE / LESS */ 
            
            #line default
            #line hidden
            
            #line 15 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
int nArithmetic=2048;
            
            #line default
            #line hidden
            
            #line 16 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
int nMacroParameters=124;/*127 parameters in one macro definition in C99 in chapter 5.2.4.1 Translation limits*/
            
            #line default
            #line hidden
            this.Write(@"
#ifndef MACRO_UTILS_H
#define MACRO_UTILS_H

#ifdef __cplusplus
#include <cstring>
#include <cstddef>
extern ""C"" {
#else
#include <string.h>
#include <stddef.h>
#endif

#if (defined OPTIMIZE_RETURN_CODES)
    #define MU_FAILURE 1
#else
    #define MU_FAILURE __LINE__
#endif

/*""pointer or NULL"" macro - because when printf-ing arguments NULL is not valid for %s (section 7.1.4 of C11 standard) */
#define MU_P_OR_NULL(p) (((p)!=NULL)?(p):""NULL"")
#define MU_WP_OR_NULL(p) (((p)!=NULL)?(p):L""NULL"")

#define MU_TOSTRING_(x) #x
#define MU_TOSTRING(x) MU_TOSTRING_(x)

#define MU_IFCOMMA(N) MU_C2(MU_IFCOMMA_, N)
#define MU_IFCOMMA_0
#define MU_IFCOMMA_2
");
            
            #line 46 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=4;i<=nMacroParameters;i+=2)
            
            #line default
            #line hidden
            
            #line 47 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_IFCOMMA_");
            
            #line 48 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" ,\r\n");
            
            #line 49 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_IFCOMMALOGIC(N) MU_C2(MU_IFCOMMALOGIC_, N)\r\n#define MU_IFCOMMALOGIC_" +
                    "0 \r\n");
            
            #line 53 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=1;i<=nMacroParameters;i+=1)
            
            #line default
            #line hidden
            
            #line 54 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_IFCOMMALOGIC_");
            
            #line 55 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" ,\r\n");
            
            #line 56 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_IFCOMMA_NOFIRST(N) MU_C2(MU_IFCOMMA_NOFIRST, N)\r\n#define MU_IFCOMMA_" +
                    "NOFIRST1 \r\n");
            
            #line 60 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=2;i<=nMacroParameters;i++)
            
            #line default
            #line hidden
            
            #line 61 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_IFCOMMA_NOFIRST");
            
            #line 62 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" ,\r\n");
            
            #line 63 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_DEC(x) MU_C2(MU_DEC,x)\r\n");
            
            #line 66 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=nArithmetic;i>=1;i--)
            
            #line default
            #line hidden
            
            #line 67 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_DEC");
            
            #line 68 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 68 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-1));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 69 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_INC(x) MU_C2(MU_INC,x)\r\n");
            
            #line 72 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=nArithmetic;i>=0;i--)
            
            #line default
            #line hidden
            
            #line 73 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_INC");
            
            #line 74 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 74 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i+1));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 75 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_DIV2(x) MU_C2(MU_DIV2_,x)\r\n\r\n");
            
            #line 79 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=nArithmetic;i>=0;i--)
            
            #line default
            #line hidden
            
            #line 80 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_DIV2_");
            
            #line 81 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 81 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i/2));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 82 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 84 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
/*the below produces MOD2 for numbers*/
            
            #line default
            #line hidden
            this.Write("#define MU_MOD2(x) MU_C2(MU_MOD2_,x)\r\n");
            
            #line 86 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=nArithmetic;i>=0;i--)
            
            #line default
            #line hidden
            
            #line 87 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_MOD2_");
            
            #line 88 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 88 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i%2));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 89 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_THE_NTH_ARG(");
            
            #line 91 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=1;i<=nMacroParameters;i++)
            
            #line default
            #line hidden
            
            #line 92 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
{
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 92 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 92 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(" ... ) P");
            
            #line 92 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nMacroParameters));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n#define MU_TRIGGER_PARENTHESIS(...) ,\r\n\r\n#define MU_LPAREN (\r\n\r\n#ifdef _MSC_V" +
                    "ER\r\n#define MU_COUNT_1_OR_MORE_ARG(...) MU_THE_NTH_ARG MU_LPAREN __VA_ARGS__, \\\r" +
                    "\n");
            
            #line 100 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=nMacroParameters-1;i>=1;i--){
            
            #line default
            #line hidden
            
            #line 100 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i.ToString()+((i>1)?", ":"")));
            
            #line default
            #line hidden
            
            #line 100 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\n#define MU_MORE_THAN_1_ARG(...) MU_THE_NTH_ARG MU_LPAREN __VA_ARGS__, ");
            
            #line 101 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=nMacroParameters-2;i>=1;i--){
            
            #line default
            #line hidden
            
            #line 101 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(1));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 101 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write("0)\r\n#else\r\n#define MU_COUNT_1_OR_MORE_ARG(...) MU_THE_NTH_ARG (__VA_ARGS__, \\\r\n");
            
            #line 104 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=nMacroParameters-1;i>=1;i--){
            
            #line default
            #line hidden
            
            #line 104 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i.ToString()+((i>1)?", ":"")));
            
            #line default
            #line hidden
            
            #line 104 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\n#define MU_MORE_THAN_1_ARG(...) MU_THE_NTH_ARG(__VA_ARGS__, ");
            
            #line 105 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=nMacroParameters-2;i>=1;i--){
            
            #line default
            #line hidden
            
            #line 105 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(1));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 105 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(@" 0)
#endif

#define MU_COUNT_ARG(...) MU_C2(MU_COUNT_ARG_, MU_ISEMPTY(__VA_ARGS__))(__VA_ARGS__)
#define MU_COUNT_ARG_1(...) 0
#define MU_COUNT_ARG_0(...) MU_C1(MU_COUNT_1_OR_MORE_ARG(__VA_ARGS__))

#define MU_ISEMPTY(...) MU_C5(MU_DISPTACH_EMPTY_, MU_MORE_THAN_1_ARG(MU_TRIGGER_PARENTHESIS __VA_ARGS__ ()), MU_MORE_THAN_1_ARG(__VA_ARGS__), MU_MORE_THAN_1_ARG(__VA_ARGS__ ()), MU_MORE_THAN_1_ARG(MU_TRIGGER_PARENTHESIS __VA_ARGS__))
#define MU_DISPTACH_EMPTY_1000 1
#define MU_DISPTACH_EMPTY_0000 0
#define MU_DISPTACH_EMPTY_1100 0
#define MU_DISPTACH_EMPTY_1111 0
#define MU_DISPTACH_EMPTY_1001 0
#define MU_DISPTACH_EMPTY_1010 0


#define MU_C2_(x,y) x##y

#define MU_C2(x,y) MU_C2_(x,y)

#define MU_C3(x,y,z) MU_C2(x, MU_C2(y,z))

#define MU_C4(x,y,z, u) MU_C2(MU_C2(x,y), MU_C2(z,u))

#define MU_C5(x,y,z,u, v) MU_C2(MU_C4(x,y, z, u), v)

#define MU_C1_(x) x

#define MU_C1(x) MU_C1_(x)

#define MU_C2STRING(x,y) x y

#define MU_C3STRING(x,y,z) x y z

#define MU_C4STRING(x,y,z,u) x y z u

#define MU_C5STRING(x,y,z,u,v) x y z u v


");
            
            #line 144 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=nMacroParameters;i>=2;i--)
            
            #line default
            #line hidden
            
            #line 145 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_1_");
            
            #line 146 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 146 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 146 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 146 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\nX(P1) \\\r\nMU_FOR_EACH_1_");
            
            #line 148 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-1));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 148 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=2;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 148 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 148 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\n\r\n");
            
            #line 150 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(@"#define MU_FOR_EACH_1_1(X, P1) \
X(P1)

#ifdef _MSC_VER
#define MU_FOR_EACH_1(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_1_,MU_C1(MU_COUNT_ARG(__VA_ARGS__))) MU_LPAREN MACRO_TO_INVOKE, __VA_ARGS__)
#else
#define MU_FOR_EACH_1(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_1_,MU_C1(MU_COUNT_ARG(__VA_ARGS__))) ( MACRO_TO_INVOKE, __VA_ARGS__)
#endif

");
            
            #line 160 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=nMacroParameters;i>=2;i--)
            
            #line default
            #line hidden
            
            #line 161 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_1_KEEP_1_");
            
            #line 162 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, keep, ");
            
            #line 162 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 162 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+(j<i?", ":"")));
            
            #line default
            #line hidden
            
            #line 162 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\nX(keep, P1) \\\r\nMU_FOR_EACH_1_KEEP_1_");
            
            #line 164 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-1));
            
            #line default
            #line hidden
            this.Write("(X, keep, ");
            
            #line 164 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=2;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 164 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((j).ToString()+(j<i?", ":"")));
            
            #line default
            #line hidden
            
            #line 164 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\n\r\n\r\n");
            
            #line 167 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(@"
#define MU_FOR_EACH_1_KEEP_1_1(X, keep, P1) \
X(keep, P1)

#ifdef _MSC_VER
#define MU_FOR_EACH_1_KEEP_1(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_1_KEEP_1_, MU_C2(MU_DEC,MU_C1(MU_COUNT_ARG(__VA_ARGS__)))) MU_LPAREN MACRO_TO_INVOKE, __VA_ARGS__)
#else
#define MU_FOR_EACH_1_KEEP_1(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_1_KEEP_1_, MU_C2(MU_DEC,MU_C1(MU_COUNT_ARG(__VA_ARGS__)))) ( MACRO_TO_INVOKE, __VA_ARGS__)
#endif

");
            
            #line 178 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=nMacroParameters;i>=2;i--)
            
            #line default
            #line hidden
            
            #line 179 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_1_KEEP_2_");
            
            #line 180 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, keep1, keep2, ");
            
            #line 180 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 180 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+(j<i?", ":"")));
            
            #line default
            #line hidden
            
            #line 180 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\nX(keep1, keep2, P1) \\\r\nMU_FOR_EACH_1_KEEP_2_");
            
            #line 182 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-1));
            
            #line default
            #line hidden
            this.Write("(X, keep1, keep2, ");
            
            #line 182 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=2;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 182 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((j).ToString()+(j<i?", ":"")));
            
            #line default
            #line hidden
            
            #line 182 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\n\r\n\r\n");
            
            #line 185 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(@"
#define MU_FOR_EACH_1_KEEP_2_1(X, keep1, keep2, P1) \
X(keep1, keep2, P1)

#define MU_FOR_EACH_1_KEEP_2_0(...)

#ifdef _MSC_VER
#define MU_FOR_EACH_1_KEEP_2(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_1_KEEP_2_, MU_C2(MU_DEC,MU_C2(MU_DEC,MU_C1(MU_COUNT_ARG(__VA_ARGS__))))) MU_LPAREN MACRO_TO_INVOKE, __VA_ARGS__)
#else
#define MU_FOR_EACH_1_KEEP_2(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_1_KEEP_2_, MU_C2(MU_DEC,MU_C2(MU_DEC,MU_C1(MU_COUNT_ARG(__VA_ARGS__))))) ( MACRO_TO_INVOKE, __VA_ARGS__)
#endif

");
            
            #line 198 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=nMacroParameters;i>=4;i-=2)
            
            #line default
            #line hidden
            
            #line 199 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_2_KEEP_1_");
            
            #line 200 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, keep, ");
            
            #line 200 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 200 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+(j<i?", ":"")));
            
            #line default
            #line hidden
            
            #line 200 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\nX(keep, P1, P2) \\\r\nMU_FOR_EACH_2_KEEP_1_");
            
            #line 202 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-2));
            
            #line default
            #line hidden
            this.Write("(X, keep, ");
            
            #line 202 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=3;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 202 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((j).ToString()+(j<i?", ":"")));
            
            #line default
            #line hidden
            
            #line 202 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\n\r\n\r\n");
            
            #line 205 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(@"
#define MU_FOR_EACH_2_KEEP_1_1(...)

#define MU_FOR_EACH_2_KEEP_1_0(...)

#define MU_FOR_EACH_2_KEEP_1_2(X, keep, P1, P2) \
    X(keep, P1, P2) \

#ifdef _MSC_VER
#define MU_FOR_EACH_2_KEEP_1(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_2_KEEP_1_, MU_C2(MU_DEC,MU_C1(MU_COUNT_ARG(__VA_ARGS__)))) MU_LPAREN MACRO_TO_INVOKE, __VA_ARGS__)
#else
#define MU_FOR_EACH_2_KEEP_1(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_2_KEEP_1_, MU_C2(MU_DEC,MU_C1(MU_COUNT_ARG(__VA_ARGS__)))) ( MACRO_TO_INVOKE, __VA_ARGS__)
#endif


");
            
            #line 221 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=nMacroParameters;i>=4;i-=2)
            
            #line default
            #line hidden
            
            #line 222 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
{
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_2_KEEP_2_");
            
            #line 223 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, keep1, keep2, ");
            
            #line 223 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 223 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+(j<i?", ":"")));
            
            #line default
            #line hidden
            
            #line 223 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\nX(keep1, keep2, P1, P2) \\\r\nMU_FOR_EACH_2_KEEP_2_");
            
            #line 225 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-2));
            
            #line default
            #line hidden
            this.Write("(X, keep1, keep2, ");
            
            #line 225 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=3;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 225 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((j).ToString()+(j<i?", ":"")));
            
            #line default
            #line hidden
            
            #line 225 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\n\r\n\r\n");
            
            #line 228 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(@"
#define MU_FOR_EACH_2_KEEP_2_1(...)

#define MU_FOR_EACH_2_KEEP_2_0(...)

#define MU_FOR_EACH_2_KEEP_2_2(X, keep1, keep2, P1, P2) \
    X(keep1, keep2, P1, P2) \

#ifdef _MSC_VER
#define MU_FOR_EACH_2_KEEP_2(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_2_KEEP_2_, MU_C2(MU_DEC,MU_C2(MU_DEC,MU_C1(MU_COUNT_ARG(__VA_ARGS__))))) MU_LPAREN MACRO_TO_INVOKE, __VA_ARGS__)
#else
#define MU_FOR_EACH_2_KEEP_2(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_2_KEEP_2_, MU_C2(MU_DEC, MU_C2(MU_DEC,MU_C1(MU_COUNT_ARG(__VA_ARGS__))))) ( MACRO_TO_INVOKE, __VA_ARGS__)
#endif


#define MU_FOR_EACH_2_0(...)

#define MU_FOR_EACH_2_2(X, P1, P2) \
X(P1, P2)

");
            
            #line 249 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=4;i<=nMacroParameters;i+=2) {
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_2_");
            
            #line 250 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 250 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 250 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 250 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\nX(P1, P2) \\\r\nMU_FOR_EACH_2_");
            
            #line 252 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-2));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 252 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=3;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 252 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 252 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\n\r\n");
            
            #line 254 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_FOR_EACH_2_REVERSE_0(...)\r\n\r\n#define MU_FOR_EACH_2_REVERSE_2(X, P1, " +
                    "P2) \\\r\nX(P1, P2)\r\n\r\n");
            
            #line 261 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=4;i<=nMacroParameters;i+=2) {
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_2_REVERSE_");
            
            #line 262 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 262 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 262 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 262 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\nX(P");
            
            #line 263 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-1));
            
            #line default
            #line hidden
            this.Write(", P");
            
            #line 263 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(") \\\r\nMU_FOR_EACH_2_REVERSE_");
            
            #line 264 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-2));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 264 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=1;j<=i-2;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 264 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i-2)?", ":"")));
            
            #line default
            #line hidden
            
            #line 264 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\n\r\n");
            
            #line 266 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_FOR_EACH_1_COUNTED_0(...)\r\n\r\n#define MU_FOR_EACH_1_COUNTED_1(X, P1) " +
                    "\\\r\n    X(1, P1)\r\n\r\n");
            
            #line 273 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=2;i<=nMacroParameters;i++) {
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_1_COUNTED_");
            
            #line 274 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 274 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 274 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 274 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\nX(");
            
            #line 275 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(", P1) \\\r\nMU_FOR_EACH_1_COUNTED_");
            
            #line 276 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-1));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 276 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=2;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 276 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 276 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\n\r\n");
            
            #line 278 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_FOR_EACH_2_COUNTED_0(...)\r\n\r\n#define MU_FOR_EACH_2_COUNTED_2(X, P1, " +
                    "P2) \\\r\n    X(2, P1, P2)\r\n\r\n");
            
            #line 285 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=4;i<=nMacroParameters;i+=2) {
            
            #line default
            #line hidden
            this.Write("#define MU_FOR_EACH_2_COUNTED_");
            
            #line 286 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 286 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=1;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 286 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 286 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(") \\\r\nX(");
            
            #line 287 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(", P1, P2) \\\r\nMU_FOR_EACH_2_COUNTED_");
            
            #line 288 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-2));
            
            #line default
            #line hidden
            this.Write("(X, ");
            
            #line 288 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var j=3;j<=i;j++){
            
            #line default
            #line hidden
            this.Write("P");
            
            #line 288 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(j.ToString()+((j<i)?", ":"")));
            
            #line default
            #line hidden
            
            #line 288 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\n\r\n");
            
            #line 290 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#ifdef _MSC_VER\r\n#define MU_FOR_EACH_2(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_" +
                    "2_, MU_C1(MU_COUNT_ARG(__VA_ARGS__))) MU_LPAREN MACRO_TO_INVOKE, __VA_ARGS__)\r\n/" +
                    "*the COUNTED breed of MU_FOR_EACH macro invokes a macro with 3 parameters: 1st b" +
                    "eing the count of invocation. For example.\r\nMU_FOR_EACH_2_COUNTER(MACRO, a,b,c,d" +
                    ",e,f) will result in \r\nMACRO(6, a,b)\r\nMACRO(4, c,d)\r\nMACRO(2, e,f)\r\nThis macro e" +
                    "xists because we need a \"stop condition\" in outputting COMMA... when calling a f" +
                    "unction f(a,b,c,d) cannot be f(a,b,c,d,) <=doesn\'t compile (as opposed to enum d" +
                    "efinition)\r\n*/\r\n#define MU_FOR_EACH_2_COUNTED(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR" +
                    "_EACH_2_COUNTED_, MU_C1(MU_COUNT_ARG(__VA_ARGS__))) MU_LPAREN MACRO_TO_INVOKE, _" +
                    "_VA_ARGS__)\r\n#define MU_FOR_EACH_1_COUNTED(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EA" +
                    "CH_1_COUNTED_, MU_C1(MU_COUNT_ARG(__VA_ARGS__))) MU_LPAREN MACRO_TO_INVOKE, __VA" +
                    "_ARGS__)\r\n\r\n/*MU_FOR_EACH_2_REVERSE acts just like MU_FOR_EACH_2, but in reverse" +
                    " order. Example:\r\nMU_FOR_EACH_2_REVERSE(X,a,b,c,d,e,f) => X(e,f) X(c,d) X (a, b)" +
                    " in this order */\r\n#define MU_FOR_EACH_2_REVERSE(MACRO_TO_INVOKE, ...) MU_C2(MU_" +
                    "FOR_EACH_2_REVERSE_, MU_C1(MU_COUNT_ARG(__VA_ARGS__))) MU_LPAREN MACRO_TO_INVOKE" +
                    ", __VA_ARGS__)\r\n#else\r\n#define MU_FOR_EACH_2(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_" +
                    "EACH_2_, MU_C1(MU_COUNT_ARG(__VA_ARGS__))) ( MACRO_TO_INVOKE, __VA_ARGS__)\r\n#def" +
                    "ine MU_FOR_EACH_2_COUNTED(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_2_COUNTED_, MU" +
                    "_C1(MU_COUNT_ARG(__VA_ARGS__))) ( MACRO_TO_INVOKE,  __VA_ARGS__)\r\n#define MU_FOR" +
                    "_EACH_1_COUNTED(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_1_COUNTED_, MU_C1(MU_COU" +
                    "NT_ARG(__VA_ARGS__))) ( MACRO_TO_INVOKE,  __VA_ARGS__)\r\n#define MU_FOR_EACH_2_RE" +
                    "VERSE(MACRO_TO_INVOKE, ...) MU_C2(MU_FOR_EACH_2_REVERSE_, MU_C1(MU_COUNT_ARG(__V" +
                    "A_ARGS__))) ( MACRO_TO_INVOKE, __VA_ARGS__)\r\n#endif\r\n\r\n#ifdef _MSC_VER\r\n#define " +
                    "MU_EXPAND_OR_MU_C1(x) x\r\n#else\r\n#define MU_EXPAND_OR_MU_C1(...) __VA_ARGS__\r\n#en" +
                    "dif\r\n\r\n#define MU_EXPAND_ARGS(...) __VA_ARGS__\r\n#define MU_EXPAND_TWICE(...) MU_" +
                    "EXPAND_ARGS(__VA_ARGS__)\r\n\r\n#define MU_DO_0(MACRO, ...) \\\r\nMACRO(0, __VA_ARGS__)" +
                    "\r\n\r\n");
            
            #line 326 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
for(var i=1;i<=nArithmetic;i++){
            
            #line default
            #line hidden
            this.Write("#define MU_DO_");
            
            #line 327 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("(MACRO, ...) \\\r\nMACRO(");
            
            #line 328 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(", __VA_ARGS__) \\\r\nMU_DO_");
            
            #line 329 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i-1));
            
            #line default
            #line hidden
            this.Write("(MACRO, __VA_ARGS__)\r\n\r\n\r\n");
            
            #line 332 "G:\repos\azure-umqtt-c\deps\azure-macro-utils-c\macro_utils_h_generator\macro_utils.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n#define MU_DO(TIMES, MACRO, ...) MU_C2(MU_DO_, TIMES)(MACRO, __VA_ARGS__)\r\n\r\n\r\n" +
                    "/* we need some sort of macro that does:\r\nMU_IF(0, \"true\", \"false\") => \"false\"\r\n" +
                    "MU_IF(1, \"true\", \"false\") => \"true\"\r\nMU_IF(X, \"true\", \"false\") => \"true\"\r\n*/\r\n\r\n" +
                    "#define MU_INTERNALIF(x) MU_INTERNALIF##x\r\n#define MU_INTERNALIF0\r\n\r\n#define MU_" +
                    "ISZERO(x) MU_COUNT_ARG(MU_INTERNALIF(x))\r\n\r\n#define MU_IF(condition, trueBranch," +
                    " falseBranch) MU_C2(MU_IF,MU_ISZERO(condition))(trueBranch, falseBranch)\r\n#defin" +
                    "e MU_IF0(trueBranch, falseBranch) falseBranch\r\n#define MU_IF1(trueBranch, falseB" +
                    "ranch) trueBranch\r\n\r\n\r\n/*the following macro want to eat empty arguments from a " +
                    "list */\r\n/*examples:                                                   */\r\n/*MU_" +
                    "EAT_EMPTY_ARGS(, , X) expands to X                       */\r\n\r\n#define MU_EXPAND" +
                    "_TO_NOTHING(arg)\r\n#define MU_EAT_EMPTY_ARG(arg_count, arg) MU_IF(MU_ISEMPTY(arg)" +
                    ",,arg) MU_IF(MU_ISEMPTY(arg),MU_EXPAND_TO_NOTHING,MU_IFCOMMALOGIC)(MU_DEC(arg_co" +
                    "unt))\r\n#define MU_EAT_EMPTY_ARGS(...) MU_FOR_EACH_1_COUNTED(MU_EAT_EMPTY_ARG, __" +
                    "VA_ARGS__)\r\n\r\n#define MU_DEFINE_ENUMERATION_CONSTANT(x) x,\r\n/*MU_DEFINE_ENUM_WIT" +
                    "HOUT_INVALID goes to header*/\r\n#define MU_DEFINE_ENUM_WITHOUT_INVALID(enumName, " +
                    "...) typedef enum MU_C2(enumName, _TAG) { MU_FOR_EACH_1(MU_DEFINE_ENUMERATION_CO" +
                    "NSTANT, __VA_ARGS__)} enumName; \\\r\n    extern const char* MU_C2(enumName,Strings" +
                    ")(enumName value); \\\r\n    extern int MU_C2(enumName, _FromString)(const char* en" +
                    "umAsString, enumName* destination);\r\n\r\n// this macro is a wrapper on top of MU_D" +
                    "EFINE_ENUM_WITHOUT_INVALID, adding an _INVALID value as the first enum value in " +
                    "the enum\r\n#define MU_DEFINE_ENUM(enumName, ...) \\\r\n    MU_DEFINE_ENUM_WITHOUT_IN" +
                    "VALID(enumName, MU_C2(enumName, _INVALID), __VA_ARGS__)\r\n\r\n#define MU_DEFINE_ENU" +
                    "MERATION_CONSTANT_AS_WIDESTRING(x) MU_C2(L, MU_TOSTRING(x)) , \r\n#define MU_DEFIN" +
                    "E_ENUMERATION_CONSTANT_AS_STRING(x) MU_TOSTRING(x) , \r\n/*MU_DEFINE_ENUM_STRINGS_" +
                    "WITHOUT_INVALID goes to .c*/\r\n#define MU_DEFINE_ENUM_STRINGS_WITHOUT_INVALID(enu" +
                    "mName, ...) const char* MU_C2(enumName, StringStorage)[MU_COUNT_ARG(__VA_ARGS__)" +
                    "] = {MU_FOR_EACH_1(MU_DEFINE_ENUMERATION_CONSTANT_AS_STRING, __VA_ARGS__)}; \\\r\nc" +
                    "onst char* MU_C2(enumName,Strings)(enumName value)                \\\r\n{          " +
                    "                                                        \\\r\n    if((int)value<0 |" +
                    "| (int)value>=MU_COUNT_ARG(__VA_ARGS__))      \\\r\n    {                          " +
                    "                                    \\\r\n        /*this is an error case*/        " +
                    "                          \\\r\n        return \"NULL\";                             " +
                    "                \\\r\n    }                                                        " +
                    "      \\\r\n    else                                                           \\\r\n " +
                    "   {                                                              \\\r\n        ret" +
                    "urn MU_C2(enumName, StringStorage)[value];              \\\r\n    }                " +
                    "                                              \\\r\n}                              " +
                    "                                    \\\r\nint MU_C2(enumName, _FromString)(const ch" +
                    "ar* enumAsString, enumName* destination)  \\\r\n{                                  " +
                    "                                             \\\r\n    if(                         " +
                    "                                                \\\r\n        (enumAsString==NULL) " +
                    "|| (destination==NULL)                             \\\r\n    )                     " +
                    "                                                      \\\r\n    {                  " +
                    "                                                         \\\r\n        return MU_FA" +
                    "ILURE;                                                      \\\r\n    }            " +
                    "                                                               \\\r\n    else      " +
                    "                                                                  \\\r\n    {      " +
                    "                                                                     \\\r\n        " +
                    "size_t i;                                                               \\\r\n     " +
                    "   for(i=0;i<MU_COUNT_ARG(__VA_ARGS__);i++)                                \\\r\n  " +
                    "      {                                                                       \\\r" +
                    "\n            if(strcmp(enumAsString, MU_C2(enumName, StringStorage)[i])==0)     " +
                    " \\\r\n            {                                                               " +
                    "    \\\r\n                *destination = (enumName)i;                              " +
                    "       \\\r\n                return 0;                                             " +
                    "          \\\r\n            }                                                      " +
                    "             \\\r\n        }                                                       " +
                    "                \\\r\n        return MU_FAILURE;                                   " +
                    "                   \\\r\n    }                                                     " +
                    "                      \\\r\n}                                                      " +
                    "                         \\\r\n\r\n// this macro is a wrapper on top of MU_DEFINE_ENU" +
                    "M_STRINGS_WITHOUT_INVALID, adding an _INVALID value as the first enum value in t" +
                    "he enum\r\n#define MU_DEFINE_ENUM_STRINGS(enumName, ...) \\\r\n    MU_DEFINE_ENUM_STR" +
                    "INGS_WITHOUT_INVALID(enumName, MU_C2(enumName, _INVALID), __VA_ARGS__)\r\n\r\n#defin" +
                    "e MU_DEFINE_LOCAL_ENUM_WITHOUT_INVALID(enumName, ...) typedef enum MU_C2(enumNam" +
                    "e, _TAG) { MU_FOR_EACH_1(MU_DEFINE_ENUMERATION_CONSTANT, __VA_ARGS__)} enumName;" +
                    " \\\r\nstatic const char* MU_C2(enumName, StringStorage)[MU_COUNT_ARG(__VA_ARGS__)]" +
                    " = {MU_FOR_EACH_1(MU_DEFINE_ENUMERATION_CONSTANT_AS_STRING, __VA_ARGS__)}; \\\r\nst" +
                    "atic const char* MU_C2(enumName,Strings)(enumName value)         \\\r\n{           " +
                    "                                                       \\\r\n    if((int)value<0 ||" +
                    " (int)value>=MU_COUNT_ARG(__VA_ARGS__))      \\\r\n    {                           " +
                    "                                   \\\r\n        /*this is an error case*/         " +
                    "                         \\\r\n        return \"NULL\";                              " +
                    "               \\\r\n    }                                                         " +
                    "     \\\r\n    else                                                           \\\r\n  " +
                    "  {                                                              \\\r\n        retu" +
                    "rn MU_C2(enumName, StringStorage)[value];              \\\r\n    }                 " +
                    "                                             \\\r\n}\r\n\r\n// this macro is a wrapper " +
                    "on top of MU_DEFINE_LOCAL_ENUM_WITHOUT_INVALID, adding an _INVALID value as the " +
                    "first enum value in the enum\r\n#define MU_DEFINE_LOCAL_ENUM(enumName, ...) \\\r\n   " +
                    " MU_DEFINE_LOCAL_ENUM_WITHOUT_INVALID(enumName, MU_C2(enumName, _INVALID), __VA_" +
                    "ARGS__)\r\n\r\n// this macro returns the number of enum values (taking into account " +
                    "that an invalid value is generated)\r\n#define MU_ENUM_VALUE_COUNT(...) (MU_COUNT_" +
                    "ARG(__VA_ARGS__) + 1)\r\n\r\n// this macro returns the number of enum 2 values (taki" +
                    "ng into account that an invalid value is generated)\r\n#define MU_ENUM_2_VALUE_COU" +
                    "NT(...) ((MU_COUNT_ARG(__VA_ARGS__) / 2) + 1)\r\n\r\n#define MU_ENUM_TO_STRING(enumN" +
                    "ame, enumValue) MU_C2(enumName, Strings)(enumValue)\r\n#define MU_STRING_TO_ENUM(s" +
                    "tringValue, enumName, addressOfEnumVariable) MU_C2(enumName, _FromString)(string" +
                    "Value, addressOfEnumVariable)\r\n\r\n#define MU_EMPTY()\r\n#define MACRO_UTILS_DELAY(i" +
                    "d) id MU_EMPTY MU_LPAREN )\r\n\r\n#define MU_DEFINE_ENUMERATION_CONSTANT_2(enumerati" +
                    "onConstant, constantExpression) enumerationConstant = constantExpression,\r\n\r\n#de" +
                    "fine MU_DECLARE_ENUM_STRINGS_2(enumIdentifier, ...) extern const char* MU_C3(MU_" +
                    ", enumIdentifier,_ToString)(enumIdentifier enumerationConstant);\r\n\r\n#define MU_D" +
                    "EFINE_ENUM_2_WITHOUT_INVALID(enumIdentifier, ... ) typedef enum MU_C2(enumIdenti" +
                    "fier, _TAG) {MU_FOR_EACH_2(MU_DEFINE_ENUMERATION_CONSTANT_2, __VA_ARGS__)} enumI" +
                    "dentifier; \\\r\n    MU_DECLARE_ENUM_STRINGS_2(enumIdentifier, __VA_ARGS__)\r\n\r\n// t" +
                    "his macro is a wrapper on top of MU_DEFINE_ENUM, adding an _INVALID value as the" +
                    " first enum value in the enum\r\n#define MU_DEFINE_ENUM_2(enumName, ...) \\\r\n    MU" +
                    "_DEFINE_ENUM_2_WITHOUT_INVALID(enumName, MU_C2(enumName, _INVALID), (int)0xDDDDD" +
                    "DDD, __VA_ARGS__)\r\n\r\ntypedef struct ENUM_VALUE_AND_STRING_TAG\r\n{\r\n    int value;" +
                    "\r\n    const char* valueAsString;\r\n}ENUM_VALUE_AND_STRING;\r\n\r\n#define MU_DEFINE_E" +
                    "NUM_VALUE_AND_STRING(enumerationConstant, constantExpression) {enumerationConsta" +
                    "nt, MU_TOSTRING(enumerationConstant)},\r\n#define MU_DEFINE_ENUM_STRINGS_2(enumIde" +
                    "ntifier, ... ) static const ENUM_VALUE_AND_STRING MU_C2(enumIdentifier, _ValuesA" +
                    "ndStrings)[MU_DIV2(MU_COUNT_ARG(__VA_ARGS__))] ={MU_FOR_EACH_2(MU_DEFINE_ENUM_VA" +
                    "LUE_AND_STRING, __VA_ARGS__)}; \\\r\nconst char* MU_C3(MU_, enumIdentifier,_ToStrin" +
                    "g)(enumIdentifier value)                                                        " +
                    "                                                                                " +
                    "               \\\r\n{                                                             " +
                    "                                                                                " +
                    "                                                                       \\\r\n    fo" +
                    "r(size_t i=0;i<sizeof(MU_C2(enumIdentifier, _ValuesAndStrings))/sizeof(MU_C2(enu" +
                    "mIdentifier, _ValuesAndStrings)[0]);i++)                                        " +
                    "                                                     \\\r\n    {                   " +
                    "                                                                                " +
                    "                                                                                " +
                    "                             \\\r\n        if(MU_C2(enumIdentifier, _ValuesAndStrin" +
                    "gs)[i].value == (int)value)                                                     " +
                    "                                                                                " +
                    "        \\\r\n        {                                                            " +
                    "                                                                                " +
                    "                                                                \\\r\n            r" +
                    "eturn MU_C2(enumIdentifier, _ValuesAndStrings)[i].valueAsString;                " +
                    "                                                                                " +
                    "                                           \\\r\n        }                         " +
                    "                                                                                " +
                    "                                                                                " +
                    "                   \\\r\n    }                                                     " +
                    "                                                                                " +
                    "                                                                           \\\r\n  " +
                    "  return \"NULL\";                                                                " +
                    "                                                                                " +
                    "                                                   \\\r\n}                         " +
                    "                                                                                " +
                    "                                                                                " +
                    "                           \\\r\n\r\n#define MU_ENUM_TO_STRING_2(enumIdentifier, valu" +
                    "e) MU_C3(MU_, enumIdentifier,_ToString)(value)\r\n\r\n#define MU_DEFINE_STRUCT_FIELD" +
                    "(fieldType, fieldName) fieldType fieldName;\r\n\r\n/*MU_DEFINE_STRUCT allows creatin" +
                    "g a struct typedef based on a list of fields*/\r\n#define MU_DEFINE_STRUCT(structN" +
                    "ame, ...) typedef struct MU_C2(structName, _TAG) { MU_FOR_EACH_2(MU_DEFINE_STRUC" +
                    "T_FIELD, __VA_ARGS__)} structName;\r\n\r\n// this macro allows counting of elements " +
                    "in an array\r\n#define MU_COUNT_ARRAY_ITEMS(A) (sizeof(A)/sizeof((A)[0]))\r\n\r\n#ifde" +
                    "f __cplusplus\r\n}\r\n#endif\r\n\r\n#endif /*MACRO_UTILS_H*/\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class macro_utilsBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
